[project]
name = "homellmcoder"
version = "0.1.0"
description = "A Home LLM Coder application"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
