# This is a safe space to test code generated by the LLM.
# Use the chat to ask the AI to write Python scripts, then paste them here.
# You can execute the code by selecting it, right-clicking, and choosing 'Execute Selection'.

print("Hello from the sandbox!")
